coverage:
  status:
    project:
      default:
        target: 80
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: true
    patch:
        enabled: false